name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: ./
        with:
          enterprise: octodemo
          github-token: ${{ secrets.TOKEN }}
          job-summary: true
          csv: true